// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WebApplication1.PJATK_APBD_Cw4_s27746.Infrastructure;

#nullable disable

namespace WebApplication1.Migrations
{
    [DbContext(typeof(DataBaseContext))]
    [Migration("20260527202827_seedingV2")]
    partial class seedingV2
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("WebApplication1.PJATK_APBD_Cw4_s27746.Models.ComponentManufacturers", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Abbreviation")
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<DateOnly>("FoundationDate")
                        .HasColumnType("date");

                    b.Property<string>("FullName")
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.HasKey("Id");

                    b.ToTable("ComponentManufacturers", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Abbreviation = "INTEL",
                            FoundationDate = new DateOnly(1968, 7, 18),
                            FullName = "Intel Corporation"
                        },
                        new
                        {
                            Id = 2,
                            Abbreviation = "AMD",
                            FoundationDate = new DateOnly(1969, 5, 1),
                            FullName = "Advanced Micro Devices"
                        },
                        new
                        {
                            Id = 3,
                            Abbreviation = "NVIDIA",
                            FoundationDate = new DateOnly(1993, 4, 5),
                            FullName = "Nvidia Corporation"
                        });
                });

            modelBuilder.Entity("WebApplication1.PJATK_APBD_Cw4_s27746.Models.ComponentTypes", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Abbreviation")
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("Name")
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.HasKey("Id");

                    b.ToTable("ComponentTypes", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Abbreviation = "CPU",
                            Name = "Central Processing Unit"
                        },
                        new
                        {
                            Id = 2,
                            Abbreviation = "GPU",
                            Name = "Graphics Processing Unit"
                        },
                        new
                        {
                            Id = 3,
                            Abbreviation = "RAM",
                            Name = "Random Access Memory"
                        });
                });

            modelBuilder.Entity("WebApplication1.PJATK_APBD_Cw4_s27746.Models.Components", b =>
                {
                    b.Property<string>("Code")
                        .HasColumnType("char(10)");

                    b.Property<int>("ComponentManufacturersId")
                        .HasColumnType("int");

                    b.Property<int>("ComponentTypesId")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.HasKey("Code");

                    b.HasIndex("ComponentManufacturersId");

                    b.HasIndex("ComponentTypesId");

                    b.ToTable("Components", (string)null);

                    b.HasData(
                        new
                        {
                            Code = "CPU0000001",
                            ComponentManufacturersId = 1,
                            ComponentTypesId = 1,
                            Description = "High-end CPU",
                            Name = "Intel Core i9"
                        },
                        new
                        {
                            Code = "GPU0000001",
                            ComponentManufacturersId = 3,
                            ComponentTypesId = 2,
                            Description = "High-end GPU",
                            Name = "RTX 4090"
                        },
                        new
                        {
                            Code = "RAM0000001",
                            ComponentManufacturersId = 2,
                            ComponentTypesId = 3,
                            Description = "Fast RAM",
                            Name = "DDR5 32GB"
                        });
                });

            modelBuilder.Entity("WebApplication1.PJATK_APBD_Cw4_s27746.Models.PCComponents", b =>
                {
                    b.Property<int>("PCId")
                        .HasColumnType("int");

                    b.Property<string>("ComponentCode")
                        .HasColumnType("char(10)");

                    b.Property<int>("amount")
                        .HasColumnType("int");

                    b.HasKey("PCId", "ComponentCode");

                    b.HasIndex("ComponentCode");

                    b.ToTable("PCComponents", (string)null);

                    b.HasData(
                        new
                        {
                            PCId = 1,
                            ComponentCode = "CPU0000001",
                            amount = 1
                        },
                        new
                        {
                            PCId = 1,
                            ComponentCode = "GPU0000001",
                            amount = 2
                        },
                        new
                        {
                            PCId = 2,
                            ComponentCode = "RAM0000001",
                            amount = 4
                        });
                });

            modelBuilder.Entity("WebApplication1.PJATK_APBD_Cw4_s27746.Models.PCs", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("created_at")
                        .HasColumnType("datetime");

                    b.Property<int>("stock")
                        .HasColumnType("int");

                    b.Property<int>("warranty")
                        .HasColumnType("int");

                    b.Property<float>("weight")
                        .HasColumnType("float(5)");

                    b.HasKey("Id");

                    b.ToTable("PCs", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "ASUS51287",
                            created_at = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            stock = 25,
                            warranty = 5,
                            weight = 10f
                        },
                        new
                        {
                            Id = 2,
                            Name = "Gaming Beast X",
                            created_at = new DateTime(2026, 2, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            stock = 5,
                            warranty = 36,
                            weight = 12f
                        },
                        new
                        {
                            Id = 3,
                            Name = "Office Mini Pro",
                            created_at = new DateTime(2026, 3, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            stock = 12,
                            warranty = 24,
                            weight = 4f
                        });
                });

            modelBuilder.Entity("WebApplication1.PJATK_APBD_Cw4_s27746.Models.Components", b =>
                {
                    b.HasOne("WebApplication1.PJATK_APBD_Cw4_s27746.Models.ComponentManufacturers", "ComponentManufacturer")
                        .WithMany("Components")
                        .HasForeignKey("ComponentManufacturersId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("WebApplication1.PJATK_APBD_Cw4_s27746.Models.ComponentTypes", "ComponentType")
                        .WithMany("Components")
                        .HasForeignKey("ComponentTypesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ComponentManufacturer");

                    b.Navigation("ComponentType");
                });

            modelBuilder.Entity("WebApplication1.PJATK_APBD_Cw4_s27746.Models.PCComponents", b =>
                {
                    b.HasOne("WebApplication1.PJATK_APBD_Cw4_s27746.Models.Components", "Components")
                        .WithMany("PCcomponents")
                        .HasForeignKey("ComponentCode")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("WebApplication1.PJATK_APBD_Cw4_s27746.Models.PCs", "PCs")
                        .WithMany("PCcomponents")
                        .HasForeignKey("PCId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Components");

                    b.Navigation("PCs");
                });

            modelBuilder.Entity("WebApplication1.PJATK_APBD_Cw4_s27746.Models.ComponentManufacturers", b =>
                {
                    b.Navigation("Components");
                });

            modelBuilder.Entity("WebApplication1.PJATK_APBD_Cw4_s27746.Models.ComponentTypes", b =>
                {
                    b.Navigation("Components");
                });

            modelBuilder.Entity("WebApplication1.PJATK_APBD_Cw4_s27746.Models.Components", b =>
                {
                    b.Navigation("PCcomponents");
                });

            modelBuilder.Entity("WebApplication1.PJATK_APBD_Cw4_s27746.Models.PCs", b =>
                {
                    b.Navigation("PCcomponents");
                });
#pragma warning restore 612, 618
        }
    }
}
